### ISSUE TITLE
Create a flag  for just fetching the input and outputs with only  contest id

### ISSUE THREAD

**Issue by TheNinza** [TheNinza/codeforces-contest#1]
For example
```sh
codeforces-contest --id=1234
```
or
```sh
codeforces-contest -i 1234
```
should fetch the input and outputs for the contest with id 1234

**Comment by shikhar13012001** [comment]
I would like to work on this @TheNinza , could you please assign it to me

**Comment by TheNinza** [comment]
Sure @shikhar13012001 , go ahead

**Comment by TheNinza** [comment]
Sure @shikhar13012001 ,
To create a flag, simply add the object in the cli.js. Following is the file with flags. 
https://github.com/TheNinza/codeforces-contest/blob/93f62b3759205da366f106b3825cc8ebf8cf6434/utils/cli.js#L4-L19

You should add a new object in the flags object. for example, for creating the --url flag with -u alias i have added the url object in line 5. You should do the same for for --id flag

then you import the flag value in the index.js like following

https://github.com/TheNinza/codeforces-contest/blob/93f62b3759205da366f106b3825cc8ebf8cf6434/index.js#L17


Then you must modify the following line to call fetchIO function to if id is present
https://github.com/TheNinza/codeforces-contest/blob/93f62b3759205da366f106b3825cc8ebf8cf6434/index.js#L22

It should be something like 
```js
(id || url) && (await fetchIO(url, id, folder, language));
```

In the utils/fetchIO.js add logic to fetch contests with id
