### ISSUE TITLE
Add checks to validate the url before trying to fetch.

### ISSUE THREAD

**Issue by TheNinza** [TheNinza/codeforces-contest#2]
Following checks should be done on the input of --url flag
1. The url should be a valid codeforces contest url (i.e. https://codeforces.com/contest/ID)

**Comment by Theta-Dev** [comment]
I'd like to work on this, @TheNinza. Could you assign it to me?

**Comment by mounicasruthi** [comment]
Hey @TheNinza could I work on this issue?

**Comment by TheNinza** [comment]
Sure @mounicasruthi , go ahead
